using DotAPicker.Models;
using System.Collections.Generic;
using System.Linq;

namespace DotAPicker.DAL
{
    public static class SeedData
    { 
        public static void Seed(DotAContext db)
        {
            var users = new List<User> {
                new User { Name = User.DEFAULT_USER,
                           Email = "default@user.com",
                           CurrentPatch = "7.33c",
                           ShowDeprecatedRelationships = false,
                           ShowDeprecatedTips = false,
                           LabelOptions = "Pusher|Nuker|Support|Disabler|Pure Damage|Agility|DoT|Strength|Intelligence|Carry|Melee|Ranged",
                           ProfileType = ProfileTypes.ReadOnly
                },
            };
            users.First().SetNewPassword("password");

            users.ForEach(u => db.Users.Add(u));
            db.SaveChanges(true);
            var defaultID = db.Users.First().Id;

            var heroes = new List<Hero> {
                new Hero { UserId = defaultID, Name = "Dazzle" },
                new Hero { UserId = defaultID, Name = "Drow Ranger" },
                new Hero { UserId = defaultID, Name = "Earthshaker" },
                new Hero { UserId = defaultID, Name = "Lich", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Lina" },
                new Hero { UserId = defaultID, Name = "Lion" },
                new Hero { UserId = defaultID, Name = "Mirana" },
                new Hero { UserId = defaultID, Name = "Morphling" },
                new Hero { UserId = defaultID, Name = "Necrophos" },
                new Hero { UserId = defaultID, Name = "Puck" },
                new Hero { UserId = defaultID, Name = "Pudge" },
                new Hero { UserId = defaultID, Name = "Razor" },
                new Hero { UserId = defaultID, Name = "Sand King" },
                new Hero { UserId = defaultID, Name = "Storm Spirit" },
                new Hero { UserId = defaultID, Name = "Tidehunter" },
                new Hero { UserId = defaultID, Name = "Vengeful Spirit" },
                new Hero { UserId = defaultID, Name = "Windranger" },
                new Hero { UserId = defaultID, Name = "Witch Doctor", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Slardar" },
                new Hero { UserId = defaultID, Name = "Enigma" },
                new Hero { UserId = defaultID, Name = "Faceless Void" },
                new Hero { UserId = defaultID, Name = "Tiny", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Venomancer" },
                new Hero { UserId = defaultID, Name = "Clockwerk" },
                new Hero { UserId = defaultID, Name = "Dark Seer" },
                new Hero { UserId = defaultID, Name = "Sniper", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Pugna" },
                new Hero { UserId = defaultID, Name = "Beastmaster" },
                new Hero { UserId = defaultID, Name = "Enchantress" },
                new Hero { UserId = defaultID, Name = "Leshrac" },
                new Hero { UserId = defaultID, Name = "Shadow Fiend" },
                new Hero { UserId = defaultID, Name = "Weaver" },
                new Hero { UserId = defaultID, Name = "Night Stalker" },
                new Hero { UserId = defaultID, Name = "Spectre", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Doom" },
                new Hero { UserId = defaultID, Name = "Bloodseeker" },
                new Hero { UserId = defaultID, Name = "Kunkka" },
                new Hero { UserId = defaultID, Name = "Riki" },
                new Hero { UserId = defaultID, Name = "Broodmother" },
                new Hero { UserId = defaultID, Name = "Jakiro" },
                new Hero { UserId = defaultID, Name = "Batrider" },
                new Hero { UserId = defaultID, Name = "Dragon Knight" },
                new Hero { UserId = defaultID, Name = "Warlock", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Lifestealer" },
                new Hero { UserId = defaultID, Name = "Death Prophet" },
                new Hero { UserId = defaultID, Name = "Ursa" },
                new Hero { UserId = defaultID, Name = "Bounty Hunter" },
                new Hero { UserId = defaultID, Name = "Silencer" },
                new Hero { UserId = defaultID, Name = "Clinkz" },
                new Hero { UserId = defaultID, Name = "Outworld Devourer" },
                new Hero { UserId = defaultID, Name = "Bane" },
                new Hero { UserId = defaultID, Name = "Shadow Demon" },
                new Hero { UserId = defaultID, Name = "Lycan" },
                new Hero { UserId = defaultID, Name = "Phantom Lancer" },
                new Hero { UserId = defaultID, Name = "Treant Protector" },
                new Hero { UserId = defaultID, Name = "Gyrocopter" },
                new Hero { UserId = defaultID, Name = "Chaos Knight" },
                new Hero { UserId = defaultID, Name = "Phantom Assassin" },
                new Hero { UserId = defaultID, Name = "Rubick" },
                new Hero { UserId = defaultID, Name = "Luna" },
                new Hero { UserId = defaultID, Name = "Io" },
                new Hero { UserId = defaultID, Name = "Undying" },
                new Hero { UserId = defaultID, Name = "Disruptor" },
                new Hero { UserId = defaultID, Name = "Nyx Assassin" },
                new Hero { UserId = defaultID, Name = "Keeper of the Light" },
                new Hero { UserId = defaultID, Name = "Visage" },
                new Hero { UserId = defaultID, Name = "Magnus" },
                new Hero { UserId = defaultID, Name = "Centaur Warrunner" },
                new Hero { UserId = defaultID, Name = "Slark" },
                new Hero { UserId = defaultID, Name = "Timbersaw", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Medusa" },
                new Hero { UserId = defaultID, Name = "Troll Warlord" },
                new Hero { UserId = defaultID, Name = "Skywrath Mage", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Ember Spirit" },
                new Hero { UserId = defaultID, Name = "Legion Commander" },
                new Hero { UserId = defaultID, Name = "Terrorblade" },
                new Hero { UserId = defaultID, Name = "Techies" },
                new Hero { UserId = defaultID, Name = "Oracle" },
                new Hero { UserId = defaultID, Name = "Winter Wyvern" },
                new Hero { UserId = defaultID, Name = "Underlord" },
                new Hero { UserId = defaultID, Name = "Monkey King" },
                new Hero { UserId = defaultID, Name = "Anti-Mage", AltNames = "Antimage AM", Notes = "" },
                new Hero { UserId = defaultID, Name = "Ogre Magi", AltNames = "om", Notes = "" },
                new Hero { UserId = defaultID, Name = "Pangolier" },
                new Hero { UserId = defaultID, Name = "Dark Willow", AltNames = "dw", Notes = "" },
                new Hero { UserId = defaultID, Name = "Spirit Breaker", AltNames = "sb barafu", Notes = "", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Sven", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Chen", Preference = HeroPreference.Hated },
                new Hero { UserId = defaultID, Name = "Crystal Maiden", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Bristleback", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Invoker", Preference = HeroPreference.Hated },
                new Hero { UserId = defaultID, Name = "Juggernaut", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Omniknight", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Viper", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Axe", Preference = HeroPreference.Disliked },
                new Hero { UserId = defaultID, Name = "Brewmaster", Preference = HeroPreference.Disliked },
                new Hero { UserId = defaultID, Name = "Elder Titan", Preference = HeroPreference.Disliked },
                new Hero { UserId = defaultID, Name = "Naga Siren", Preference = HeroPreference.Hated },
                new Hero { UserId = defaultID, Name = "Meepo", Preference = HeroPreference.Hated },
                new Hero { UserId = defaultID, Name = "Wraith King", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Zeus", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Tinker", Preference = HeroPreference.Disliked },
                new Hero { UserId = defaultID, Name = "Tusk", Preference = HeroPreference.Disliked },
                new Hero { UserId = defaultID, Name = "Templar Assassin", AltNames = "ta, lanaya", Notes = "TA is a mid hero; she benefits a lot from early levels and needs them to get kills so she can get deso/blink and snowball. Absent early farm she can be very underwhelming.", Preference = HeroPreference.Favorite },
                new Hero { UserId = defaultID, Name = "Lone Druid", AltNames = "LD", Notes = "LD can be played as a bear-focused hero or as a sniper-style damage dealer.", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Ancient Apparition", AltNames = "aa", Notes = "", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Arc Warden", AltNames = "aw", Notes = "I have notes here! I'm curious what this looks like when it's really long! I have notes here! I'm curious what this looks like when it's really long! I have notes here! I'm curious what this looks like when it's really long! I have notes here! I'm curious what this looks like when it's really long! I have notes here! I'm curious what this looks like when it's really long! I have notes here! I'm curious what this looks like when it's really long! ", Preference = HeroPreference.Hated },
                new Hero { UserId = defaultID, Name = "Queen of Pain", AltNames = "QoP", Notes = "" },
                new Hero { UserId = defaultID, Name = "Phoenix", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Earth Spirit", AltNames = "", Notes = "Preferred because I think I'll like him a lot more when I suck less", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Nature's Prophet", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Huskar", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Shadow Shaman", Preference = HeroPreference.Preferred },
                new Hero { UserId = defaultID, Name = "Alchemist", Preference = HeroPreference.Disliked },
                new Hero { UserId = defaultID, Name = "Abaddon", AltNames = "", Notes = "Abaddon is versatile and can be played as core or support. I prefer playing him as a support, maxing aphotic shield so my carry is unkillable.", Preference = HeroPreference.Preferred }
            };
            heroes.ForEach(u => db.Heroes.Add(u));
            db.SaveChanges(true);
            db.SaveChanges(true);
        }
    }
}